export enum EstadoPedido {
    SIN_PEDIR = "SIN_PEDIR",
    PENDIENTE_PAGO = "PENDIENTE_PAGO",
    PAGADO = "PAGADO",
    PREPARACION = "PREPARACION",
    PENDIENTE_ENTREGA = "PENDIENTE_ENTREGA",
    EN_CAMINO = "EN_CAMINO",
    CANCELADO = "CANCELADO",
    NOTA_CREDITO = "NOTA_CREDITO",
    COMPLETADO = "COMPLETADO"
}